#+title: Example SPARQL queries for evolomero.evolbio.mpg.de
#+property: header-args:sparql :url https://evolomero.evolbio.mpg.de/qlever :async yes :results output table replace :cache yes :exports both :noweb yes
#+property: header-args:ttl :eval no :noweb yes
#+property: header-args:bash :noweb yes :eval query

* README first!
:PROPERTIES:
:ID:       8235c0c9-0ef5-46f3-a826-8e4b2c67a7be
:END:
This readme file is the source for all example queries in this directory. Example queries should be edited here, not in the /ttl/ files. To (re-)create
the /ttl/ files, run =org-babel-tangle= in emacs.

* Setup
:PROPERTIES:
:ID:       6045d575-e758-402e-a654-0e6cfe179e51
:END:

** SPARQL Prefixes
:PROPERTIES:
:ID:       62a37deb-cf19-46b5-acae-764cdfb04543
:END:
Here we define commonly used prefixes in =sparql= syntax to be included into
=sparql= source code blocks by adding the line =<<idr-prefixes>>= somewhere in
the block (probably somewhere near the top ;).

#+name: sparql-prefixes
#+begin_src sparql :eval no
  PREFIX owl: <http://www.w3.org/2002/07/owl#>
  PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  PREFIX dcterms: <http://purl.org/dc/terms/>
  PREFIX dc: <http://purl.org/dc/elements/1.1/>
  PREFIX omecore: <https://ld.openmicroscopy.org/core/>
  PREFIX omekg: <https://ld.openmicroscopy.org/omekg#>
  PREFIX obda: <https://w3id.org/obda/vocabulary#>
  PREFIX xml: <http://www.w3.org/XML/1998/namespace/>
  PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
  PREFIX kv: <http://www.openmicroscopy.org/ns/default/>
  PREFIX idr: <https://idr.openmicroscopy.org/>
  prefix evolomero: <https://evolomero.evolbio.mpg.de/>
  PREFIX up: <http://purl.uniprot.org/core/>
  PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
#+end_src

** TTL prefixes
:PROPERTIES:
:ID:       00c0e6ad-e529-41e3-be5b-907ad2a55bc8
:END:
Common prefixes in =ttl= syntax go here and can be included into =ttl= snippets by adding a =<<ttl-prefixes>>= noweb block.

#+name: ttl-prefixes
#+caption: RDF prefix declarations in turtle syntax
#+begin_src ttl
  @PREFIX dc: <http://purl.org/dc/elements/1.1/>
  @PREFIX dcterms: <http://purl.org/dc/terms/>
  @PREFIX ex: <https://sparql.uniprot.org/.well-known/sparql-examples/> .
  @PREFIX idr: <https://idr.openmicroscopy.org/> .
  @PREFIX evolomero: <https://evolomero.evolbio.mpg.de/> .
  @PREFIX kv: <http://www.openmicroscopy.org/ns/default/> .
  @PREFIX obda: <https://w3id.org/obda/vocabulary#> .
  @PREFIX omecore: <https://ld.openmicroscopy.org/core/> .
  @PREFIX omekg: <https://ld.openmicroscopy.org/omekg#> >
  @PREFIX owl: <http://www.w3.org/2002/07/owl#> >
  @PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
  @PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
  @PREFIX schema: <https://schema.org/> .
  @PREFIX sh: <http://www.w3.org/ns/shacl#> .
  @PREFIX xml: <http://www.w3.org/XML/1998/namespace/> .
  @PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> .

#+end_src

** SPARQL endpoint URL
:PROPERTIES:
:ID:       9e78c00b-3cee-4c11-a4ea-36ab08362808
:END:
#+name: idr_sparql_endpoint_url
#+begin_src ttl
  <https://evolomero.evolbio.mpg.de/vkg/sparql>
#+end_src

* Example queries
:PROPERTIES:
:ID:       988fb935-973a-49e0-b700-461fdf65f5ec
:END:

** All projects with names and IDs
:PROPERTIES:
:ID:       da8e59c5-d071-4e02-b07e-3cf9c6fb989a
:END:
#+begin_src ttl :noweb-ref 001-comment
  Select all projects and list their names and ids.
#+end_src
#+name: 001-skeleton
#+begin_src ttl :tangle 001--all_projects.ttl :exports none
  <<ttl-prefixes>>

  ex:001 a sh:SPARQLExecutable, sh:SPARQLSelectExecutable ;
      rdfs:comment "<<001-comment>>"^^rdf:HTML ;
      sh:prefixes _:sparql_example_prefixes ;
      schema:keywords "project" ;
      schema:target <<idr_sparql_endpoint_url>> ;
      sh:select """
  <<001-sparql>>
  """ .
#+end_src

#+name: 001-sparql
#+begin_src sparql :exports both
  <<sparql-prefixes>>

  select ?project ?name ?id where {
    ?project a omecore:Project ;
             rdfs:label ?name ;
             dc:identifier ?id .
    }
#+end_src

#+RESULTS[96735a1ec71d54e7bf8f0bf85e816adbe2e50bb7]: 001-sparql
| project                                      | name                 |  id |
|----------------------------------------------+----------------------+-----|
| https://evolomero.evolbio.mpg.de/Project/102 | Escamilla2026        | 102 |
| https://evolomero.evolbio.mpg.de/Project/51  | Kyomen..Kaucka--2026 |  51 |

** Gene names and uniprot proteins
:PROPERTIES:
:ID:       edac2060-06c6-4937-b8fb-24b06de3716a
:END:

#+name: sparql.gene-protein
#+begin_src sparql
  <<sparql-prefixes>>

  select * where {
    ?img a omecore:Image;
         omecore:hasAnnotation/omecore:mapEntry ?map .
        ?map omecore:key ?key;
             omecore:value ?gene .
          filter(?key = "Gene")
    #   {
    #   select ?tax_val where {
    #        ?map omecore:key ?key;
    #        omecore:value ?tax_val .
    #     filter(?key = "ncbitaxon")
    #     }
    #   }
    # }
    bind(iri("http://purl.uniprot.org/taxonomy/10090") as ?taxon)
    service <https://sparql.uniprot.org/sparql>
    {
      select ?protein where {
      ?protein a up:Protein;
              up:organism <http://purl.uniprot.org/taxonomy/10090> ;
              up:mnemonic ?mnemonic .
      filter(concat(ucase(str(?gene)), "_MOUSE") = ?mnemonic)
        }
    }
    }
  limit 100
#+end_src

#+RESULTS[6f387101edcb396329361b183d7209f661f1860e]: sparql.gene-protein
| img | map | key | gene | taxon | protein |
|-----+-----+-----+------+-------+---------|

#+begin_src sparql :url https://sparql.uniprot.org/sparql
  PREFIX up: <http://purl.uniprot.org/core/>
  select * where
  {
        ?protein a up:Protein;
                up:organism <http://purl.uniprot.org/taxonomy/10090> ;
                up:mnemonic ?mnemonic .
        # filter(contains(lcase(?mnemonic), "dlx2"))
      filter(concat(ucase("Dlx2"), "_MOUSE") = ?mnemonic)
        }
      limit 10
#+end_src

#+RESULTS[76d2418fdd81184adbb8e0e8df9f3437ac0e6fbe]:
| protein                                | mnemonic   |
|----------------------------------------+------------|
| http://purl.uniprot.org/uniprot/P40764 | DLX2_MOUSE |
